# Generated by Django 5.0.6 on 2024-08-29 18:23

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Введите номер телефона', max_length=12, unique=True, verbose_name='Телефон')),
                ('invite_code', models.CharField(default=users.models.generate_invite_code, max_length=6, unique=True, verbose_name='код приглашения')),
                ('invite_pole', models.TextField(blank=True, max_length=6, null=True, verbose_name='поле для приглашения')),
            ],
        ),
    ]
