# Generated by Django 5.0.6 on 2024-08-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(help_text='Введите номер телефона', max_length=12, unique=True, verbose_name='Телефон')),
                ('phone_code', models.CharField(max_length=4, verbose_name='код авторизации')),
                ('invite_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='код приглашения')),
                ('invite_pole', models.TextField(blank=True, max_length=6, null=True, verbose_name='поле для приглашения')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
    ]
