# Generated by Django 5.0.6 on 2024-08-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_pole',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='поле для приглашения'),
        ),
    ]
