# Generated by Django 5.0.6 on 2024-08-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_invite_pole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_pole',
            field=models.TextField(blank=True, max_length=6, null=True, verbose_name='поле для приглашения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='код авторизации'),
        ),
    ]
