# Generated by Django 5.0.6 on 2024-08-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_password_alter_user_invite_pole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='код авторизации'),
        ),
    ]
